[MFLOG|0|2024-12-05T21:56:05.990870Z|runtime|e40a2056-41f9-4940-a64b-bc8d066b6259]Downloading artifacts:   0%|          | 0/12 [00:00<?, ?it/s]Downloading artifacts:   8%|▊         | 1/12 [00:00<00:00, 1148.18it/s]Downloading artifacts:  17%|█▋        | 2/12 [00:00<00:00, 1820.05it/s]Downloading artifacts:  25%|██▌       | 3/12 [00:00<00:00, 2512.56it/s]Downloading artifacts:  33%|███▎      | 4/12 [00:00<00:00, 3160.15it/s]Downloading artifacts:  42%|████▏     | 5/12 [00:00<00:00, 3739.57it/s]Downloading artifacts:  50%|█████     | 6/12 [00:00<00:00, 4264.67it/s]Downloading artifacts:  58%|█████▊    | 7/12 [00:00<00:00, 4772.45it/s]Downloading artifacts:  67%|██████▋   | 8/12 [00:00<00:00, 5252.73it/s]Downloading artifacts:  75%|███████▌  | 9/12 [00:00<00:00, 3820.34it/s]Downloading artifacts:  83%|████████▎ | 10/12 [00:00<00:00, 4011.38it/s]Downloading artifacts:  92%|█████████▏| 11/12 [00:00<00:00, 128.84it/s] Downloading artifacts: 100%|██████████| 12/12 [00:00<00:00, 40.38it/s] Downloading artifacts: 100%|██████████| 12/12 [00:00<00:00, 40.38it/s]Downloading artifacts: 100%|██████████| 12/12 [00:00<00:00, 40.25it/s]
[MFLOG|0|2024-12-05T21:56:06.954594Z|runtime|1975d35b-fe78-4bf3-ae99-b3e3a03ed8b7]2024/12/05 22:56:06 INFO mlflow.sagemaker: Using the python_function flavor for deployment!
[MFLOG|0|2024-12-05T21:56:09.405848Z|runtime|955bb6fe-cace-440c-a6e6-722885c176b7]<flow Deployment step deployment> failed:
[MFLOG|0|2024-12-05T21:56:09.425532Z|runtime|4c1f81e8-84e6-4955-9ba2-6207ba92a939]    Internal error
[MFLOG|0|2024-12-05T21:56:09.428687Z|runtime|a1719c2a-fcec-4995-a617-b74f084f13b7]Traceback (most recent call last):
[MFLOG|0|2024-12-05T21:56:09.428794Z|runtime|c81d4a74-6673-4b9e-a67a-3897a6a2bbbf]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 2785, in get_deployment
[MFLOG|0|2024-12-05T21:56:09.428874Z|runtime|db6b280a-25b6-4a55-a1b2-7dbda69b5aa8]    return sage_client.describe_endpoint(EndpointName=name)
[MFLOG|0|2024-12-05T21:56:09.428933Z|runtime|284adea5-eb23-4852-b704-36aeb0030c6e]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.429001Z|runtime|3e43960f-3df4-4314-a360-1954cfd7f602]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
[MFLOG|0|2024-12-05T21:56:09.429066Z|runtime|124d6769-a131-4991-af8a-30f3c4028490]    return self._make_api_call(operation_name, kwargs)
[MFLOG|0|2024-12-05T21:56:09.429120Z|runtime|fc802f18-ebc7-407b-b5e6-4badb4df12b1]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.429185Z|runtime|915748e3-824c-4977-8b9e-c7da651c2848]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
[MFLOG|0|2024-12-05T21:56:09.429243Z|runtime|1932af05-ef51-4c93-95b4-db44d537041e]    raise error_class(parsed_response, operation_name)
[MFLOG|0|2024-12-05T21:56:09.429296Z|runtime|db16d853-a356-4007-a318-f2a89505b234]botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DescribeEndpoint operation: Could not find endpoint "dailyweather01".
[MFLOG|0|2024-12-05T21:56:09.429350Z|runtime|b3c3458b-d177-4469-aac8-e66478264566]
[MFLOG|0|2024-12-05T21:56:09.429405Z|runtime|d96844cc-1b99-43d1-962f-c7b866ea52c7]During handling of the above exception, another exception occurred:
[MFLOG|0|2024-12-05T21:56:09.429460Z|runtime|51a1709d-1509-4ffb-860c-20c4c7443f4d]
[MFLOG|0|2024-12-05T21:56:09.429519Z|runtime|7d3305fe-b75b-4e6d-9958-f94e9484c1df]Traceback (most recent call last):
[MFLOG|0|2024-12-05T21:56:09.429576Z|runtime|adebaeab-5b5b-4e63-ada3-a07fe879a44e]  File "/Users/gabriel/Documents/ML_school/ml.school.opensource/kaggle/code/deployment.py", line 248, in _deploy_to_sagemaker
[MFLOG|0|2024-12-05T21:56:09.429628Z|runtime|a2e4cca4-f5b6-4c28-9d40-8f227688c27c]    deployment = deployment_client.get_deployment(self.endpoint)
[MFLOG|0|2024-12-05T21:56:09.429678Z|runtime|d0e9b97e-024b-42f2-a723-c62d71b40c94]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.429729Z|runtime|5f946c45-3967-4a11-8d23-bf131fdaaafc]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 2787, in get_deployment
[MFLOG|0|2024-12-05T21:56:09.429788Z|runtime|f8de4468-5d71-407a-974b-da646f8a735b]    raise MlflowException(
[MFLOG|0|2024-12-05T21:56:09.429838Z|runtime|210e7c0c-2cc3-4fc3-ad21-d23853299c20]mlflow.exceptions.MlflowException: There was an error while retrieving the deployment: An error occurred (ValidationException) when calling the DescribeEndpoint operation: Could not find endpoint "dailyweather01".
[MFLOG|0|2024-12-05T21:56:09.429900Z|runtime|7b20d070-7bf3-4793-8faa-f7d536723f9d]
[MFLOG|0|2024-12-05T21:56:09.429950Z|runtime|3869cda7-80ad-4f05-bb58-3c2ee19671b1]
[MFLOG|0|2024-12-05T21:56:09.430046Z|runtime|aebe88bc-d591-4019-b8af-af407df72cc3]During handling of the above exception, another exception occurred:
[MFLOG|0|2024-12-05T21:56:09.430096Z|runtime|d8fbc732-fc27-45c5-a016-d54a14c1c35c]
[MFLOG|0|2024-12-05T21:56:09.430154Z|runtime|6b23aa91-9323-4601-9446-9df3b93c6be6]Traceback (most recent call last):
[MFLOG|0|2024-12-05T21:56:09.430206Z|runtime|519c4903-9211-4c7d-b6c2-104e4e265ef2]  File "/tmp/tmp29uz6cu2/metaflow/cli.py", line 1166, in main
[MFLOG|0|2024-12-05T21:56:09.430257Z|runtime|b481eacf-1d10-461f-b420-eb32ebd61156]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2024-12-05T21:56:09.430308Z|runtime|c2461c23-c4c0-4dce-8932-3c033e5876c8]  File "/tmp/tmp29uz6cu2/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2024-12-05T21:56:09.430361Z|runtime|1eced12a-70a5-4f8e-ad89-4b4fc9828f24]    return func(args, kwargs)
[MFLOG|0|2024-12-05T21:56:09.696752Z|runtime|b35adbb5-1c74-44f9-a8ae-2fc9e70e9b35]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.696923Z|runtime|f4694e9e-f408-430a-ab73-8f82bd9d35e8]  File "/tmp/tmp29uz6cu2/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2024-12-05T21:56:09.696969Z|runtime|2862fe3b-fcd4-4cc9-a843-0b48e91a5e52]    return self.main(args, kwargs)
[MFLOG|0|2024-12-05T21:56:09.697007Z|runtime|4b3bf97f-9fb9-463d-923c-fc8edd11f8fa]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697040Z|runtime|2cbd1bb2-87d2-4847-9142-688b11f0d510]  File "/tmp/tmp29uz6cu2/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2024-12-05T21:56:09.697071Z|runtime|be77b98b-619c-4450-832f-de23f914d7f3]    rv = self.invoke(ctx)
[MFLOG|0|2024-12-05T21:56:09.697103Z|runtime|ba12ce9f-e4a0-4e98-9530-e256ee322971]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697134Z|runtime|ea72a573-2b3c-4716-9969-dbf3bb38b5c5]  File "/tmp/tmp29uz6cu2/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2024-12-05T21:56:09.697164Z|runtime|1ab74789-7345-49d6-bf60-9c32694cb6b5]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2024-12-05T21:56:09.697194Z|runtime|acd77dcf-9b5b-488c-8b61-d317aa260fce]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697225Z|runtime|0f891c0c-a715-413d-a9e3-ce3f781c9e3b]  File "/tmp/tmp29uz6cu2/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2024-12-05T21:56:09.697255Z|runtime|9ef08408-9613-4d49-b815-4fa2567c01d3]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2024-12-05T21:56:09.697285Z|runtime|cc3c8249-43f6-4274-8b4c-78755cd4df8a]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697316Z|runtime|ec0d8d6d-a701-4677-96ec-1c06087a5e49]  File "/tmp/tmp29uz6cu2/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2024-12-05T21:56:09.697346Z|runtime|7c2a1b5a-d4e6-44c0-93b8-3c4fe8744d5a]    return callback(args, kwargs)
[MFLOG|0|2024-12-05T21:56:09.697375Z|runtime|374624d3-24d8-4e22-8743-f78e167a590b]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697405Z|runtime|16b614aa-e811-4d70-828d-a67d711d432f]  File "/tmp/tmp29uz6cu2/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2024-12-05T21:56:09.697438Z|runtime|54eb3c78-0e75-4060-9cb3-1af58ecd223d]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2024-12-05T21:56:09.697467Z|runtime|133648af-4a7c-44a5-b89c-627e9b31e18c]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697496Z|runtime|ffeaee20-82d6-467e-ac64-9a63ea71ff7c]  File "/tmp/tmp29uz6cu2/metaflow/cli.py", line 469, in step
[MFLOG|0|2024-12-05T21:56:09.697554Z|runtime|5538b3f1-f1ac-48a0-a9be-4465e4d626a5]    task.run_step(
[MFLOG|0|2024-12-05T21:56:09.697587Z|runtime|9a6776cc-c32f-4f04-afd7-c365566fb039]  File "/tmp/tmp29uz6cu2/metaflow/task.py", line 653, in run_step
[MFLOG|0|2024-12-05T21:56:09.697620Z|runtime|fa924096-fe82-4485-a0f1-feff7aaa6b6d]    self._exec_step_function(step_func)
[MFLOG|0|2024-12-05T21:56:09.697650Z|runtime|2c5cefc2-0a24-4036-8f43-bca42f1ef471]  File "/tmp/tmp29uz6cu2/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2024-12-05T21:56:09.697680Z|runtime|5085d013-97ad-4a44-89de-b40d3b3105b7]    step_function()
[MFLOG|0|2024-12-05T21:56:09.697709Z|runtime|5785f6fe-1f1d-4bbe-9cd2-5afa9a2ce1ab]  File "/Users/gabriel/Documents/ML_school/ml.school.opensource/kaggle/code/deployment.py", line 134, in deployment
[MFLOG|0|2024-12-05T21:56:09.697740Z|runtime|20003a56-ea33-44af-97f2-0c855e14e9a6]    self._deploy_to_sagemaker()
[MFLOG|0|2024-12-05T21:56:09.697770Z|runtime|10ca3d72-a208-485d-82fa-fadbcad66100]  File "/Users/gabriel/Documents/ML_school/ml.school.opensource/kaggle/code/deployment.py", line 268, in _deploy_to_sagemaker
[MFLOG|0|2024-12-05T21:56:09.697804Z|runtime|b19e473f-b6f7-449f-92f7-7503a9a2f09a]    self._create_sagemaker_deployment(
[MFLOG|0|2024-12-05T21:56:09.697835Z|runtime|34721260-d43d-484a-ab85-9e76ad0697fa]  File "/Users/gabriel/Documents/ML_school/ml.school.opensource/kaggle/code/deployment.py", line 324, in _create_sagemaker_deployment
[MFLOG|0|2024-12-05T21:56:09.697866Z|runtime|9a304b0e-ef52-44ef-82a2-7a85d8c1c9b0]    deployment_client.create_deployment(
[MFLOG|0|2024-12-05T21:56:09.697895Z|runtime|7e604836-4bc0-48f2-a58b-7a4c452ca6bc]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 2333, in create_deployment
[MFLOG|0|2024-12-05T21:56:09.697925Z|runtime|009956f1-fc7e-43de-8d01-1368c2ecdc41]    app_name, flavor = _deploy(
[MFLOG|0|2024-12-05T21:56:09.697955Z|runtime|e8bdf04d-2310-41c8-89de-53cc64d3ec98]                       ^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.697988Z|runtime|c45a31b1-9522-4022-8da9-3e0417578f9f]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 412, in _deploy
[MFLOG|0|2024-12-05T21:56:09.698018Z|runtime|d8539455-4037-49c6-9c35-6937397bea46]    execution_role_arn = _get_assumed_role_arn(assume_role_credentials)
[MFLOG|0|2024-12-05T21:56:09.698048Z|runtime|afcc13f3-b6ba-441e-9896-2b69d58b34a4]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.698081Z|runtime|64b3514b-1641-4126-ae48-ac611a080c04]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 1228, in _get_assumed_role_arn
[MFLOG|0|2024-12-05T21:56:09.698111Z|runtime|78abe29a-2e45-41ae-b46d-cd1c3ee61710]    role_response = iam_client.get_role(RoleName=role_name)
[MFLOG|0|2024-12-05T21:56:09.698145Z|runtime|591f720d-83e0-4d30-b945-702dfc35e719]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.698179Z|runtime|ee0edbf3-eb3a-4ba8-9b65-db30dfc23591]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
[MFLOG|0|2024-12-05T21:56:09.698212Z|runtime|c58f611e-63c3-4dbc-8a46-8c375425859a]    return self._make_api_call(operation_name, kwargs)
[MFLOG|0|2024-12-05T21:56:09.698242Z|runtime|a2d963e8-c548-42b9-b4fc-6578960d0071]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-12-05T21:56:09.698271Z|runtime|2d48d567-d112-4ad3-a70b-f4a2a90fed31]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/abeec5193171f93/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
[MFLOG|0|2024-12-05T21:56:09.698302Z|runtime|2457952e-494b-4575-8e19-07588ccf28b4]    raise error_class(parsed_response, operation_name)
[MFLOG|0|2024-12-05T21:56:09.698332Z|runtime|77dd1c3a-3900-4354-8886-015ffc6632ef]botocore.errorfactory.NoSuchEntityException: An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name gabrielt cannot be found.
[MFLOG|0|2024-12-05T21:56:09.698363Z|runtime|333abe7f-57aa-4de2-a230-e8df5caee04c]
[MFLOG|0|2024-12-05T21:56:09.698874Z|runtime|0a8dcd34-9bb9-427a-9517-c53d1a27a65a]Task failed.