[MFLOG|0|2024-11-14T23:31:25.739551Z|runtime|f91eebb4-6669-4639-8235-018cd00bbbef]2024/11/15 00:31:25 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[MFLOG|0|2024-11-14T23:31:25.769390Z|runtime|3fac45c0-167e-4428-971f-fe17dae6470a]2024/11/15 00:31:25 WARNING mlflow.utils.autologging_utils: MLflow xgboost autologging is known to be compatible with 1.4.2 <= xgboost <= 2.1.1, but the installed version is 2.1.2. If you encounter errors during autologging, try upgrading / downgrading xgboost to a compatible version, or try upgrading MLflow.
[MFLOG|0|2024-11-14T23:31:25.776570Z|runtime|69e5e25d-dcfc-425a-9ee1-2f9e50e3f77a]2024/11/15 00:31:25 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
[MFLOG|0|2024-11-14T23:31:29.331219Z|runtime|d875fb4b-6006-4adc-9a13-f6d62fe6c749]2024/11/15 00:31:28 ERROR mlflow.xgboost: Failed to log feature importance plot. XGBoost autologging will ignore the failure and continue. Exception: 
[MFLOG|0|2024-11-14T23:31:37.986403Z|runtime|cc0fe862-150f-4e96-800f-34bd17ed062a]Traceback (most recent call last):
[MFLOG|0|2024-11-14T23:31:37.987324Z|runtime|787a5991-08f0-4aa6-bc68-3f6a3e8b12f1]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 738, in train_impl
[MFLOG|0|2024-11-14T23:31:37.987408Z|runtime|d185c0ed-6eca-4246-a349-39e935b7aca5]    log_feature_importance_plot(features, importance, imp_type)
[MFLOG|0|2024-11-14T23:31:37.987470Z|runtime|f026dd0c-02f0-4962-83aa-7a30faec5020]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 552, in log_feature_importance_plot
[MFLOG|0|2024-11-14T23:31:37.987526Z|runtime|1d281a82-8fd4-4f42-8135-5a57437fc1e8]    import matplotlib.pyplot as plt
[MFLOG|0|2024-11-14T23:31:37.987578Z|runtime|0555a60d-4e4e-494f-9a3a-7b9fd7aa843a]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 1270, in <module>
[MFLOG|0|2024-11-14T23:31:37.987620Z|runtime|4f8ccc27-97ec-478c-a3e7-75acebe6d56b]    rcParams['backend'] = os.environ.get('MPLBACKEND')
[MFLOG|0|2024-11-14T23:31:37.987679Z|runtime|9e42997d-0cad-464d-ae70-3e8cf0e43bc0]    ~~~~~~~~^^^^^^^^^^^
[MFLOG|0|2024-11-14T23:31:37.987730Z|runtime|4a36fcd6-4044-47a5-b2ce-d0503c417670]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 738, in __setitem__
[MFLOG|0|2024-11-14T23:31:37.987774Z|runtime|8cb93777-f772-49d5-9daf-e4f113428f84]    raise ValueError(f"Key {key}: {ve}") from None
[MFLOG|0|2024-11-14T23:31:37.987839Z|runtime|5649144c-5bbc-44d5-a32c-6c44a6ab9f5f]ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
[MFLOG|0|2024-11-14T23:31:37.987903Z|runtime|11922468-fccb-47df-b369-f32128649bd6]2024/11/15 00:31:29 INFO mlflow.tracking._tracking_service.client: üèÉ View run 1731627072434019 at: http://127.0.0.1:5000/#/experiments/0/runs/0c8cd70bc11746339afadb8bd009d4f8.
[MFLOG|0|2024-11-14T23:31:37.987996Z|runtime|c399cdde-9212-41b8-972e-8e3d7b105c20]2024/11/15 00:31:29 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
